### ISSUE TITLE
Error when running ribotish tisdiff

### ISSUE THREAD

**Issue by marcasriv** [zhpn1024/ribotish#1]
Hi,

I've been trying to run the whole pipeline included in Ribo-seq TIS Hunter(ribotish quality, ribotish predict and ribotish tisdiff ) with four different replicates of RiboSeq data.  I've had no issues so far with the first two functions, but when running tisdiff 

`ribotish tisdiff -1 Sample_6/test6.txt -2 Sample_7/test7.txt -a Sample_6/sample6_sort.bam -b  Sample_7/sample6_sort.bam -g //index/genome.gtf -o diff2.txt -v
` 

I've retrieved the following errors 
`Traceback (most recent call last):
  File "/home/user/RiboSeq/project/bin/ribotish", line 14, in <module>
    import os, sys, argparse, time
  File "/home/user/RiboSeq/project/bin/ribotish", line 35, in main
    commands[cmd].run(args)
  File "/home/user/RiboSeq/project/local/lib/python2.7/site-packages/ribotish/run/tisdiff.py", line 229, in run
    for result in pred_iter:
  File "/home/user/RiboSeq/project/local/lib/python2.7/site-packages/ribotish/run/tisdiff.py", line 375, in _get_tis
    ttis = ribo.multiRibo(t, bamlist[i], offlist[i], compatible = compatible, mis = compatiblemis, paired = paired)
  File "/home/user/RiboSeq/project/local/lib/python2.7/site-packages/ribotish/zbio/ribo.py", line 489, in multiRibo
    mribo.merge(Ribo(trans, bamfiles[i], offset = offset, offdict = offdict[i], compatible = compatible, mis = mis, paired = paired))
  File "/home/user/RiboSeq/project/local/lib/python2.7/site-packages/ribotish/zbio/ribo.py", line 71, in __init__
    off = offset(r, offdict)
TypeError: 'list' object is not callable
`

Also, as I ran it in verbose mode, I retrieved the following printed- on- screen messages

` 
No offset parameter file found for Sample_6/sample1_sort.bam. Using default offset (12).
No offset parameter file found for Sample_7/sample1_sort.bam. Using default offset (12).
Loading 2 TIS data...
7 TISs in Sample_6/test6.txt.
23 TISs in Sample_7/test7.txt.
24 TISs in total.
Reading bams...
`

Could it be the error due to the fact of having a different number of predicted TIS in both Sample_6/test6.txt and Sample_7/test7.txt ? I've tried to filter both files so only the intersecting common predicted TIS are fed as an input to ribotish tisdiff, but still getting the same errors. 

Would you have any idea of how to fix this issue?

The prediction files( Sample_6/test6.txt and  Sample_7/test7.txt) were generated by running
`ribotish predict -t /home/user/Sample_7/sample7_sort.bam  -g //index/genome.gtf -f //index/genome.fa --tispara 12 --altcodons CTG,TTG --harr -p 78 -o test7.txt `

Thank you very  much!

**Comment by zhpn1024** [comment]
Hi,
The error is a bug. I'll fix it later.

By the way,
The TISDIFF module is only for quantitative TI-Seq (QTI). Your data looks like harr type TI-Seq, which is not quantitative. The differential results may be not very accurate.
The offset parameter files should be like Sample_6/sample1_sort.bam.para.py, which are generated using ribotish quality. The parameter files record estimated P-site offset values. You need to check the quality pdf figures generated by quality module. Don't forget to use -t when running TI-Seq quality.

Best,
Peng
