### ISSUE TITLE
Feature Request - Add 3' end match for RPFs

### ISSUE THREAD

**Issue by alanlorenzetti** [zhpn1024/ribotish#10]
Hi. This is a great tool!

The prokaryotic community could benefit more of it if a feature doing the same for 3' end of RPFs could be added. Seems like the 3-nt periodicity for model organisms like E. coli is easier to notice when using 3' end profile of RPFs. 

Thanks!

**Comment by zhpn1024** [comment]
Do you mean taking 3' end of RPF as positions in quality figure?

**Comment by alanlorenzetti** [comment]
Yes. Please, check Figure 6 from [this paper](https://link.springer.com/content/pdf/10.1007/s12275-020-9536-2.pdf).

![image](https://user-images.githubusercontent.com/8172418/81042292-a2f41380-8e64-11ea-9c57-254db31bd441.png)

**Comment by zhpn1024** [comment]
Got it. 
Do you want to assign P-site offset relative to 3' end?

**Comment by alanlorenzetti** [comment]
Oh, that is up to you. I don’t have sufficient expertise on the topic to judge whether this is a crucial feature. Sorry.

**Comment by zhpn1024** [comment]
The feature has been added as option '--end3' in 0.2.6.

**Comment by alanlorenzetti** [comment]
Thank you!
