### ISSUE TITLE
What dose this Horizontal line mean

### ISSUE THREAD

**Issue by shwdmsh** [zhpn1024/ribotish#13]
![image](https://user-images.githubusercontent.com/10626547/109482549-1aacc200-7ab9-11eb-9093-a5e910402c6a.png)
Hi！What dose this Horizontal line mean ?

**Comment by zhpn1024** [comment]
It is a rough way for P-site offset estimation. The line represents a threshold to determine the P-site offset in the specific frame (color) and range. The first position higher than the line are selected to calculate the P-site. No P-site is reported if no line or no in frame signal higher than the line.

**Comment by shwdmsh** [comment]
Thank you very much!

**Comment by shwdmsh** [comment]
Thank you
