### ISSUE TITLE
what the types of TisType  mean?

### ISSUE THREAD

**Issue by shwdmsh** [zhpn1024/ribotish#15]
What the types of TisType  mean?When I use the ribotish predict ,I get the many types of TisType,what dose every TisType
means ?
TisType
--
Annotated
Truncated
Novel
Internal:CDSFrameOverlap
Internal
3'UTR
5'UTR
5'UTR:CDSFrameOverlap
Extended
3'UTR:Known
3'UTR:CDSFrameOverlap
Novel:CDSFrameOverlap
Truncated:Known

**Comment by zhpn1024** [comment]
TisType: | Relative position of this TIS to annotated ORF of the transcript. 'Novel' if no ORF annotation. ':Known' means the TIS is annotated in another transcript. ':CDSOverlap' means the ORF overlaps with annotated CDS in another transcript in the same reading frame.
-- | --

**Comment by shwdmsh** [comment]
Thanks
