### ISSUE TITLE
New release for python 3

### ISSUE THREAD

**Issue by eggzilla** [zhpn1024/ribotish#2]
Hi, 
first of all thanks for developing ribotish!
We added a recipe for ribotish to bioconda to install it together with its dependencies.
See here: https://anaconda.org/bioconda/ribotish
and here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ribotish/meta.yaml
I saw that you added changes necessary to run ribotish with python 3, if you would make
a new release version we could also update the recipe to python 3.

**Comment by zhpn1024** [comment]
Thank you! I'll make a new release soon.

**Comment by eggzilla** [comment]
Thanks for releasing!
I already updated the recipe and will close the issue:
https://anaconda.org/bioconda/ribotish

**Comment by zhpn1024** [comment]
> Thanks for releasing!
> I already updated the recipe and will close the issue:
> https://anaconda.org/bioconda/ribotish

Hi,
Could you update the Ribo-TISH new version to bioconda?
Thanks!
