### ISSUE TITLE
Use of 5' mismatch reads in predict

### ISSUE THREAD

**Issue by ericmalekos** [zhpn1024/ribotish#31]
This is just a question about the implementation of the predict function.
Say I have para.py as 
offdict = {27: 11,  'm0': {27: 12}}

But after examination I decide to remove the 5' mismatch reads from the analysis. If I edit para.py to:
offdict = {27: 11}

Is that going to ignore or include the 5' mismatch reads? I don't want to include them, should I do something else?
e.g. 
'm0':{}

Thank you!

**Comment by zhpn1024** [comment]
I think it should be in this way:
offdict = {27: 11, 'm0': {}}
