### ISSUE TITLE
ribotish predict module run error

### ISSUE THREAD

**Issue by haowBio** [zhpn1024/ribotish#32]
Hellow
    when I run ribotish predict using stringtie assembly gtf which include new transcript info, it return this error
![image](https://user-images.githubusercontent.com/72370921/223890941-01c016df-d821-499b-a2a5-d60124e882f9.png)
after removing new transcript it run successfully. How can I solve it?

This is my gtf
![image](https://user-images.githubusercontent.com/72370921/223891500-a093d615-ca0d-44cf-aea3-b8f908d37fb9.png)

**Comment by zhpn1024** [comment]
The key problem is that the 'trans.strand' is '.', not '+' or '-'. Are there ways and options to assign strand in stringtie?

**Comment by haowBio** [comment]
> The key problem is that the 'trans.strand' is '.', not '+' or '-'. Are there ways and options to assign strand in stringtie?

Thank for you reply 
After deleting the transcript which which strand is '.', It run successfully.
