### ISSUE TITLE
Emplty sequence error

### ISSUE THREAD

**Issue by NastiaSkuba** [zhpn1024/ribotish#34]
Hi, I am trying to predict ORF from ribo-seq data.

My command 

```
ribotish predict -b sample.bam -g annotation.gtf -f genome.fasta -o pred.txt --longest --alt --verbose
```

Unfortunately, I am almost immediately getting an error

```
Tue Jan 23 15:12:11 2024 Loading genome...
Making fasta index for genome.fasta...
Traceback (most recent call last):
  File "/home/qbase/miniconda3/envs/ribotish-env/bin/ribotish", line 56, in <module>
    main()
  File "/home/qbase/miniconda3/envs/ribotish-env/bin/ribotish", line 34, in main
    commands[cmd].run(args)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/run/predict.py", line 132, in run
    genome = fa.Fa(args.genomefapath, verbose = args.verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 88, in __init__
    self.make_idx(idxpath)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 104, in make_idx
    self.idxarr[-1].updatels(ls)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 63, in updatels
    if ls <= 0 : raise Exception("Empty sequence!")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I tried to create new separate environment, but it did not help.
Also, QC was performed fine, I got desired result.

Here is the list of packages in the conda environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.12.12           h06a4308_0  
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
expat                     2.5.0                h6a678d5_0  
fonttools                 4.47.2                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
matplotlib                3.8.2                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.26.3                   pypi_0    pypi
openssl                   3.0.12               h7f8727e_0  
packaging                 23.2                     pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1          py312h06a4308_0  
pyparsing                 3.1.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
python                    3.12.1               h996f2a0_0  
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
ribotish                  0.2.7                    pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
setuptools                68.2.2          py312h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2023d                h04d1e81_0  
wheel                     0.41.2          py312h06a4308_0  
xz                        5.4.5                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
```

Hope for your help!
Thank you!

**Comment by zhpn1024** [comment]
The genome.fasta file has empty lines. It is not a standard indexable fasta format. You can download fasta file from public resources with genome.fasta.fai index file provided.
















At 2024-01-23 22:32:34, "Nastia" ***@***.***> wrote:

Hi, I am trying to predict ORF from ribo-seq data.

My command

ribotish predict -b sample.bam -g annotation.gtf -f genome.fasta -o pred.txt --longest --alt --verbose


Unfortunately, I am almost immediately getting an error

Tue Jan 23 15:12:11 2024 Loading genome...
Making fasta index for genome.fasta...
Traceback (most recent call last):
  File "/home/qbase/miniconda3/envs/ribotish-env/bin/ribotish", line 56, in <module>
    main()
  File "/home/qbase/miniconda3/envs/ribotish-env/bin/ribotish", line 34, in main
    commands[cmd].run(args)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/run/predict.py", line 132, in run
    genome = fa.Fa(args.genomefapath, verbose = args.verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 88, in __init__
    self.make_idx(idxpath)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 104, in make_idx
    self.idxarr[-1].updatels(ls)
  File "/home/qbase/miniconda3/envs/ribotish-env/lib/python3.12/site-packages/ribotish/zbio/fa.py", line 63, in updatels
    if ls <= 0 : raise Exception("Empty sequence!")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


I tried to create new separate environment, but it did not help.
Also, QC was performed fine, I got desired result.

Here is the list of packages in the conda environment:

# Name                           Version                   Build  Channel
_libgcc_mutex                 0.1                        main  
_openmp_mutex             5.1                       1_gnu  
bzip2                               1.0.8                h7b6447c_0  
ca-certificates           2023.12.12           h06a4308_0  
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
expat                     2.5.0                h6a678d5_0  
fonttools                 4.47.2                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
matplotlib                3.8.2                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.26.3                   pypi_0    pypi
openssl                   3.0.12               h7f8727e_0  
packaging                 23.2                     pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1          py312h06a4308_0  
pyparsing                 3.1.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
python                    3.12.1               h996f2a0_0  
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
ribotish                  0.2.7                    pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
setuptools                68.2.2          py312h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2023d                h04d1e81_0  
wheel                     0.41.2          py312h06a4308_0  
xz                        5.4.5                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  


Hope for your help!
Thank you!

**Comment by NastiaSkuba** [comment]
Thank you very much! Everything worked! 
It would be nice to describe in the manual that a genome index can be downloaded from a database.
